[DEFAULT]
cpu_allocation_ratio = 1.0
instance_name_template = instance-%(uuid)s
max_concurrent_builds = 10
reserved_host_cpus = 4
reserved_host_memory_mb = 8192
resize_confirm_window = 10800
resume_guests_state_on_host_boot = true
vif_plugging_timeout = 600

[filter_scheduler]
enabled_filters = ComputeFilter,ComputeCapabilitiesFilter,AggregateNumInstancesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,AggregateImagePropertiesIsolation,AggregateTypeAffinityFilter
shuffle_best_same_weighed_hosts = True
soft_anti_affinity_weight_multiplier = 4
weight_classes = nova.scheduler.weights.metrics.MetricsWeigher
weight_setting = cpu_weight_multiplier=1000, ram_weight_multiplier=100

[libvirt]
hw_machine_type = x86_64=q35

[workarounds]
skip_cpu_compare_on_dest = True