name: Build deploy container

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stackers-network/stn-deploy-2024.1:latest
    steps:
      - name: Check for dockerenv file
        run: cd /; find .
