name: Build deploy container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted, linux, X64]
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ghcr.io/stackers-network/stn-deploy-2024.2:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
      - name: Kick off installer
        run: |
           mkdir -p /etc/kolla
           chown $USER:$USER /etc/kolla
           cp -r /usr/local/share/kolla-ansible/etc_examples/kolla/* /etc/kolla
           #cp /usr/local/share/kolla-ansible/ansible/inventory/* .
           kolla-ansible install-deps
           find .
           pwd
           ls -la ../
           ls -la ../..
           kolla-genpwd
           sleep 20000
           kolla-ansible bootstrap-servers -i inventory/hosts
           kolla-ansible deploy -i inventory/hosts
