
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:27.2.0-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker commands
        run: |
          docker version
          docker info
          # Add your Docker commands here
          docker build -t stn-deploy .
          docker run --rm stn-deploy
