name: Build deploy container

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ANSIBLE_FORCE_COLOR: true
jobs:
  docker:
    runs-on: [self-hosted, linux, X64]
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ghcr.io/stackers-network/stn-deploy-2024.2:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Kick off deploy
        run: |
           mkdir -p /etc/kolla
           chown $USER:$USER /etc/kolla
           echo "${{ secrets.PASSWD_FILE }}" > /etc/kolla/passwords.yml
           chmod 600 /etc/kolla/passwords.yml
           cp globals.yml /etc/kolla/globals.yml
           kolla-ansible install-deps
           #kolla-genpwd
           # For initial bootstrap
           kolla-ansible bootstrap-servers -i inventory/hosts
           kolla-ansible deploy -i inventory/hosts
           # After initial bootstrap, reconfigure the deployment
           # kolla-ansible reconfigure -i inventory/hosts
